=begin
#JumpCloud APIs

# JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module JCAPIv2
  class GroupType
    
    SYSTEM_GROUP = "system_group".freeze
    USER_GROUP = "user_group".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = GroupType.constants.select{|c| GroupType::const_get(c) == value}
      raise "Invalid ENUM value #{value} for class #GroupType" if constantValues.empty?
      value
    end
  end

end
