# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:latest
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud