=begin
#JumpCloud APIs

#V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for JCAPIv1::InlineResponse200ConfigConstantAttributesValue
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse200ConfigConstantAttributesValue' do
  before do
    # run before each test
    @instance = JCAPIv1::InlineResponse200ConfigConstantAttributesValue.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse200ConfigConstantAttributesValue' do
    it 'should create an instance of InlineResponse200ConfigConstantAttributesValue' do
      expect(@instance).to be_instance_of(JCAPIv1::InlineResponse200ConfigConstantAttributesValue)
    end
  end
  describe 'test attribute "visible"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "read_only"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

